INSERT INTO funcao (nome) VALUES ('ADMINISTRADOR');
INSERT INTO funcao (nome) VALUES ('GERENTE');
INSERT INTO funcao (nome) VALUES ('NORMAL');
INSERT INTO USUARIO (NOME,PASSWORD,USERNAME,FUNCAO_ID) VALUES ('ERICKSON','123','ERICKSON',1);
INSERT INTO USUARIO (NOME,PASSWORD,USERNAME,FUNCAO_ID) VALUES ('ERINSTON','456','ERINSTO',2);
INSERT INTO USUARIO (NOME,PASSWORD,USERNAME,FUNCAO_ID) VALUES ('LUIGI','789','LUIGI',3);
