INSERT INTO funcao (nome) VALUES ('ADMINISTRADOR');
INSERT INTO funcao (nome) VALUES ('GERENTE');
INSERT INTO funcao (nome) VALUES ('NORMAL');
INSERT INTO autor (nome) VALUES ('Calvino');
INSERT INTO autor (nome) VALUES ('Arminio');
INSERT INTO USUARIO (NOME,PASSWORD,USERNAME,FUNCAO_ID) VALUES ('ERINSTON','456','ERINSTO',2);
INSERT INTO USUARIO (NOME,PASSWORD,USERNAME,FUNCAO_ID) VALUES ('LUIGI','789','LUIGI',3);
